In [1]:
import numpy as np

In [2]:
inputArray = np.array ([
    [1,2,3],
    [4,5,6]])

inputArray

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
inputArray.shape

(2, 3)

In [4]:
inputArray[1][1]

np.int64(5)

In [5]:
inputArray[0][1:]

array([2, 3])

### sorting Array

In [6]:
arr = np.array([1200,34,2,62,2])
np.sort(arr)

array([   2,    2,   34,   62, 1200])